### ISSUE TITLE
Paper Suggestion:  Monte Carlo Augmented Actor-Critic for Sparse Reward Deep Reinforcement Learning from Suboptimal Demonstrations

### ISSUE THREAD

**Issue by DuaneNielsen** [hanjuku-kaso/awesome-offline-rl#39]
Hey, sorry  I tried to do a pull request, but I could not figure it out.

Love this list you have put together, I found many good papers on the list.

Recently I came across this paper.  Strictly speaking it's not offline-RL, but it's adjacent.  Its more like the AWAC algorithm, using offline data to get a good initialization for an online agent.

[Monte Carlo Augmented Actor-Critic for Sparse Reward Deep Reinforcement Learning from Suboptimal Demonstrations](https://arxiv.org/abs/2210.07432)

So I'm not sure if it fits on the list, but it's a simple paper with a simple and elegant idea.

**Comment by aiueola** [comment]
@DuaneNielsen
 Thank your suggesting an interesting paper! Sure, let's add it to the list.

**Comment by aiueola** [comment]
https://github.com/hanjuku-kaso/awesome-offline-rl/pull/40/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R277
